DROP TABLE ta ;

CREATE TABLE ta (
    idta INTEGER PRIMARY KEY AUTOINCREMENT,
    statust INTEGER DEFAULT 0,
    status INTEGER DEFAULT 0,
    parent INTEGER DEFAULT 0,
    child INTEGER DEFAULT 0,
    script INTEGER DEFAULT 0,
    idroute VARCHAR(35) DEFAULT '',
    filename VARCHAR(256) DEFAULT '',
    frompartner VARCHAR(35) DEFAULT '',
    topartner VARCHAR(35) DEFAULT '',
    fromchannel VARCHAR(35) DEFAULT '',
    tochannel VARCHAR(35) DEFAULT '',
    editype VARCHAR(35) DEFAULT '',
    messagetype VARCHAR(35) DEFAULT '',
    alt VARCHAR(35) DEFAULT '',
    divtext VARCHAR(35) DEFAULT '',
    merge BOOLEAN DEFAULT 0,
    nrmessages INTEGER DEFAULT 1,
    testindicator VARCHAR(10) DEFAULT '',
    reference VARCHAR(70) DEFAULT '',
    frommail VARCHAR(256) DEFAULT '',
    tomail VARCHAR(256) DEFAULT '',
    charset VARCHAR(35) DEFAULT '',
    statuse INTEGER DEFAULT 0,
    retransmit BOOLEAN DEFAULT 0,
    contenttype VARCHAR(35) DEFAULT 'text/plain',
    errortext VARCHAR(1024) DEFAULT '',
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    confirmasked BOOLEAN DEFAULT 0,
    confirmed BOOLEAN DEFAULT 0,
    confirmtype VARCHAR(35) DEFAULT '',
    confirmidta INTEGER DEFAULT 0,
    envelope VARCHAR(35) DEFAULT '',
    botskey VARCHAR(35) DEFAULT '',
    cc VARCHAR(512) DEFAULT ''
) ;

